### ISSUE TITLE
Null Program state breaks `MvuComponentBuilder`

### ISSUE THREAD

**Issue by amongonz** [fabulous-dev/Fabulous#1086]
Uses of `let! model = Mvu.State` within `MvuComponentBuilder` views fail at runtime when the `Program` state is represented as null.

I think this happens because [`ComponentContext.TryGetValue` returns `ValueNone` when the underlying state is null](https://github.com/fabulous-dev/Fabulous/blob/5fcd38230b5100ac3675fe96a841fb6eb04b8e0c/src/Fabulous/ComponentContext.fs#L59-L62), assuming it's not a valid representation for the state.

This is a problem specially because values such as `()` and `None` are also represented as null, so components with state type `unit` or `option` are inherently broken. Even worse, both the [Avalonia](https://github.com/fabulous-dev/Fabulous.Avalonia/blob/765ecd172eaf5682d61043ea468c812ecb9adba4/src/Fabulous.Avalonia/AppBuilderExtensions.fs#L41-L44) and [MAUI](https://github.com/fabulous-dev/Fabulous.MauiControls/blob/b934a4397a4be9596afe85fb0d59e338899e4795/src/Fabulous.MauiControls/AppHostBuilderExtensions.fs#L45-L48) implementations wrap the top-level view with an `MvuComponentBuilder`, then provide a `Program.stateless` helper which immediately triggers this issue.

[This repro repository](https://github.com/amongonz/FabulousIssue1086) triggers the exception at the binder for the root component of the Avalonia implementation linked above.

**Comment by TimLariviere** [comment]
Hi @amongonz!

Thanks for the report.

This is indeed an issue. I also saw it happen when using a unit model `()` which is represented as `null` at runtime.

Components are still very much bleeding edge and I'm actively working on it. I will fix that issue in the next preview version.

**Comment by TimLariviere** [comment]
Fixed in https://github.com/fabulous-dev/Fabulous/releases/tag/3.0.0-pre8
