### ISSUE TITLE
Add a MAUI target

### ISSUE THREAD

**Issue by Happypig375** [fabulous-dev/Fabulous#747]
It is the next evolution of Xamarin.Forms targetting all of .NET. https://github.com/dotnet/maui

We should investigate before the .NET 6 release on how to support it.

**Comment by TimLariviere** [comment]
Yes, absolutely.

For the time being, I don't think we can do anything about it. MAUI is currently a clone of Xamarin.Forms, and I'm guessing a lot will change until the targeted release of November 2021.

Regarding the "single project - several platforms", I'm hoping the F# tooling in the various IDEs will follow the C# tooling because that will be the major blocking point for a Fabulous.MAUI.

Aside from that, Fabulous is mostly reading to accept a new framework like this one.

**Comment by TimLariviere** [comment]
An interesting link showing what MAUI could be: https://github.com/dotnet/maui/issues/28

**Comment by PureWeen** [comment]
Excited to see how this could influence Fabulous!!

Maybe Fabulous could shift away from having to just clone wrapping forms elements? Go a bit more in the direction of Comet and having it's own syntax.

**Comment by TimLariviere** [comment]
@PureWeen It will be interesting to see what this restructuring will enable!
Adapting MVVM-focused controls to the MVU style is head-scratching at times...

Comet seems to share a lot of similarities with Fabulous, except that Fabulous don't provide its own abstraction over what a control is. Comet is a lot like Xamarin.Forms on this point.
Fabulous is more akin to a MVU-enabler for existing UI frameworks.

So, depending on the actual implementation of MAUI, I think Fabulous will still need to clone wrap the various controls so we can provide our own syntax and diffing logic, while not having to reimplement all the platform renderers.

**Comment by guillaumebailleul** [comment]
Intersting, it seems that peoples are pretty sure that fabulous will implement MAUI. https://github.com/dotnet/maui/discussions/115#discussioncomment-655646

**Comment by JustinWick** [comment]
Have any decisions been made on whether or not we are getting MAUI support in Fabulous?

**Comment by TimLariviere** [comment]
@JustinWick Fabulous will support MAUI. You can see the progress here https://github.com/TimLariviere/Fabulous-new
At the same time, we're completely re-architecturing the internals of Fabulous to enable a bunch of new features (better View API, better performance and many other).

Once we figure out everything, I hope to make a compatibility layer to more easily migrate from Fabulous v1 to v2.

Anyway we're still at a very early stage.
We should be close enough to a stable release when MAUI goes live in Q2 2022

If you want some insights on Fabulous v2:
- https://github.com/TimLariviere/Fabulous-new/blob/main/docs/goals-of-v2.md
- https://github.com/fsprojects/Fabulous/issues/738

**Comment by dsyme** [comment]
@TimLariviere That is fantastic news!

**Comment by JbmOnGitHub** [comment]
@TimLariviere .NET MAUI RC2 is released now ; How much work would it take to plug Faboulus on it ?
I admit I don't realize all that this implies !

**Comment by TimLariviere** [comment]
@JbmOnGitHub Plugging a new framework to Fabulous is pretty straightforward. It's mainly about writing wrappers for the new framework to be usable in the view function. This is time consuming but fairly easy to do.

With MAUI though, there is a difficulty to solve first.
Unlike XF, MAUI gives us interfaces (`IButton`, `ILabel`, `IStackLayout`) so we need to figure out how to implement those to work with Fabulous internals (widgets & attributes).

Once it's done, we will be able to start adding wrappers to all controls and we will release preview versions of `Fabulous.Maui`.

**Comment by ChristophSchmidpeter** [comment]
@TimLariviere The [FSharp.Mobile.Templates Readme](https://github.com/fabulousfx/FSharp.Mobile.Templates#readme) lists MAUI already as a target. Does this indicate that one can build Fabulous apps with MAUI already, or has it only been added for future use?

**Comment by TimLariviere** [comment]
@ChristophSchmidpeter You can't use Fabulous with Maui yet.
Support for it is underway in #919, but to be honest there are many issues with Maui right now so it is making it difficult for us.

Regarding the error you're seeing, it has been reported here: https://github.com/fabulousfx/FSharp.Mobile.Templates/issues/21

**Comment by ChristophSchmidpeter** [comment]
@TimLariviere Thank you for the info and great to hear that support is already underway :)

**Comment by TimLariviere** [comment]
Maui is now supported. Please see https://github.com/fabulous-dev/Fabulous.MauiControls
