### ISSUE TITLE
NU1108 Cycle detected 

### ISSUE THREAD

**Issue by pipsy100** [fabulous-dev/Fabulous#877]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1108	Cycle detected. 
  Fabulous.WPF -> Fabulous -> Fabulous.XamarinForms 1.1.0 -> Fabulous (>= 1.0.0 && < 2.0.0).	Fabulous.WPF	C:\Projects\Fabulous\Fabulous.WPF\Fabulous.WPF.fsproj	1

**Comment by SergejDK** [comment]
@pipsy100 
Sorry for the late reploy but is this issue happening after you create a new project ? 

Maybe after the PR #902 is merged this issue should not be there anymore.
