### ISSUE TITLE
Question: state of Linux support?

### ISSUE THREAD

**Issue by njlr** [fabulous-dev/Fabulous#975]
I have been trying to create a "hello world" app using Fabulous, but I fear that I have an incompatible set of requirements:

 - Fabulous 2
 - .NET 6
 - Xamarin Forms
 - Linux (Ubuntu, GTK)

Is there an example of these working together?

**Comment by TimLariviere** [comment]
Xamarin.Forms doesn't officially run on .NET 6. You could [make it work](https://github.com/fabulousfx/FSharp.Mobile.Templates) but I wouldn't recommend it, especially if you plan to use any other XF NuGet packages, they would not be compatible.

With this said, the rest of your list should be ok.

Fabulous 1 and Fabulous 2 apps are both running in a .NET Standard 2.0 library.
Even though we did not provide the Linux template for v2, you could still use the Linux template from v1 and copy over your Fabulous 2 application.

Here's the GTK template from v1:
https://github.com/fsprojects/Fabulous/tree/v1.0/Fabulous.XamarinForms/samples/CounterApp/Gtk

**Comment by njlr** [comment]
> Xamarin.Forms doesn't officially run on .NET 6

Does this mean I must target an older .NET (Core) or even Mono?

**Comment by TimLariviere** [comment]
Yes. Xamarin.Forms only runs on Mono.
Xamarin as a whole started to run on .NET Core starting MAUI, and Microsoft decided against porting Xamarin.Forms to .NET 6.0
